- name: Set Web Runtime Replication Status in a cluster
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.runtime.replication.set
    isamapi:
      replicating: "{{ set_runtime_replication_replicating }}"
  when: set_runtime_replication_replicating is defined
  notify:
    - Commit Changes
