- name: Update Advanced Configuration - {{ update_advanced_configuration_key }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.advanced_configuration.update
    isamapi:
      key:       "{{ update_advanced_configuration_key }}"
      value:     "{{ update_advanced_configuration_value }}"
      sensitive: "{{ update_advanced_configuration_sensitive }}"
  notify:
    - Commit Changes
    - Restart AAC Runtime