- name: Snapshot Appliance Before Adding Management Authorization Roles
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.snapshots.create
    isamapi:
      comment: "{{ add_mgmtazn_role_comment }}"

- name: Add Management Authorization Roles
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.management_authorization.role.add
    isamapi:
      name: "{{ item }}"
  with_items: "{{ mgmtazn_role_names }}"
  when: mgmtazn_role_names is defined
  notify: Commit Changes

