# run pdadmin commands to setup ACL and POPs for AAC

- name: Run PDAdmin commands
  isamadmin:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    isamuser:  "{{ execute_isamcfg_isamuser }}"
    isampwd:   "{{ execute_isamcfg_isampwd }}"
    commands:
    - "# Create POPs"
    - "pop create oauth-pop"
    - "pop modify oauth-pop set description \"ISAM autoconfiguration tool POP\""
    - "pop modify oauth-pop set attribute eas-trigger trigger_oauth_eas"
    - "pop create rba-pop"
    - "pop modify rba-pop set description \"ISAM autoconfiguration tool POP\""
    - "pop modify rba-pop set attribute eas-trigger trigger_rba_eas"
    - "# Create ACLs"
    - "acl create isam_mobile_anyauth"
    - "acl modify isam_mobile_anyauth description \"ISAM autoconfiguration tool ACL\""
    - "acl modify isam_mobile_anyauth set group iv-admin TcmdbsvaBRrxl"
    - "acl modify isam_mobile_anyauth set group webseal-servers Tgmdbsrxl"
    - "acl modify isam_mobile_anyauth set any-other Tr"
    - "acl modify isam_mobile_anyauth set unauthenticated T"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/auth isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/ac isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/xauth isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/mga/user/mgmt/html isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/oauth/oauth20/clients isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/start_config/qr isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/oauth/oauth20/logout isam_mobile_anyauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/common/qr isam_mobile_anyauth"
    - "acl create isam_mobile_nobody"
    - "acl modify isam_mobile_nobody description \"ISAM autoconfiguration tool ACL\""
    - "acl modify isam_mobile_nobody set group iv-admin TcmdbsvaBRrxl"
    - "acl modify isam_mobile_nobody set group webseal-servers Tgmdbsrxl"
    - "acl modify isam_mobile_nobody set any-other T"
    - "acl modify isam_mobile_nobody set unauthenticated T"
    - "acl attach  /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }} isam_mobile_nobody"
    - "acl create isam_mobile_rest"
    - "acl modify isam_mobile_rest description \"ISAM autoconfiguration tool ACL\""
    - "acl modify isam_mobile_rest set group iv-admin TcmdbsvaBRrxl"
    - "acl modify isam_mobile_rest set group webseal-servers Tgmdbsrxl"
    - "acl modify isam_mobile_rest set any-other Tmdr"
    - "acl modify isam_mobile_rest set unauthenticated T"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/mga/user/mgmt/otp isam_mobile_rest"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/mga/user/mgmt/device isam_mobile_rest"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/mga/user/mgmt/questions isam_mobile_rest"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/mga/user/mgmt/grant isam_mobile_rest"
    - "acl create isam_mobile_rest_unauth"
    - "acl modify isam_mobile_rest_unauth description \"ISAM autoconfiguration tool ACL\""
    - "acl modify isam_mobile_rest_unauth set group iv-admin TcmdbsvaBRrxl"
    - "acl modify isam_mobile_rest_unauth set group webseal-servers Tgmdbsrxl"
    - "acl modify isam_mobile_rest_unauth set any-other Tmdrxl"
    - "acl modify isam_mobile_rest_unauth set unauthenticated Tmdrxl"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/apiauthsvc isam_mobile_rest_unauth"
    - "acl create isam_mobile_unauth"
    - "acl modify isam_mobile_unauth description \"ISAM autoconfiguration tool ACL\""
    - "acl modify isam_mobile_unauth set group iv-admin TcmdbsvaBRrxl"
    - "acl modify isam_mobile_unauth set group webseal-servers Tgmdbsrxl"
    - "acl modify isam_mobile_unauth set any-other Tr"
    - "acl modify isam_mobile_unauth set unauthenticated Tr"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/authsvc isam_mobile_unauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/authservice/authentication isam_mobile_unauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/oauth/oauth20/authorize isam_mobile_unauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/static isam_mobile_unauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/oauth/oauth20/session isam_mobile_unauth"
    - "acl attach /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }}/sps/oauth/oauth20/token isam_mobile_unauth"
    - "# Add HTTP Tag Value"
    - "object modify /WebSEAL/{{ common_web_root }}{{ execute_isamcfg_junction_point }} set attribute HTTP-Tag-Value user_session_id=user_session_id"
  when: common_web_root is defined and execute_isamcfg_reverseproxy_id in execute_isamcfg_reverseproxy_list
  ignore_errors: true
  register: ret_obj

- name: Output of PDAdmin command execution
  debug: msg="{{ ret_obj['data']['result'].split('\n') }}"
  when: (ret_obj|succeeded and (not ansible_check_mode))

- name: Error Messages *if* PDAdmin command failed
  debug: msg="{{ ret_obj['log'].split('\n') }}"
  when: (ret_obj|failed and (not ansible_check_mode))

