- name: Change Embedded LDAP cn=root password
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.embedded_ldap.admin.set_pw
    isamapi:
      password: "{{ set_ldap_root_pw_password }}"
  when: set_ldap_root_pw_password is defined
  notify: Commit Changes