- name: Create LMI system account user
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.sysaccount.users.create
    isamapi:
      id : "{{ add_sysaccount_id }}"
      password : "{{ add_sysaccount_password }}"
      groups : "{{ add_sysaccount_groups }}"
  when: add_sysaccount_id is defined
  notify: Commit Changes
