- name: Import URL Mapping (dynurl) - {{import_url_mapping_id}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.url_mapping.import_file
    isamapi:
      id       : "{{ import_url_mapping_id }}"
      filename : "{{ import_url_mapping_filename }}"
  when: import_url_mapping_id is defined and import_url_mapping_filename is defined
  notify: Commit Changes

# Commit changes - changes need to take effect for next steps
- meta: flush_handlers
