- name: Get Reverse Proxies
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.instance.get
  register: ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    reverseproxy_ret_obj: "{{ ret_obj }}"