# It is recommended to create a policy using LMI and export the XML file to use
# in the "policy" attribute for this task
- name: Set Access Control Policy - {{set_access_control_policy_name}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.access_control.policies.set_file
    isamapi:
      name:               "{{ set_access_control_policy_name }}"
      policy_file:        "{{ set_access_control_policy_policy_file }}"
      description:        "{{ set_access_control_policy_description }}"
      attributesrequired: "{{ set_access_control_policy_attributesrequired }}"
      dialect:            "{{ set_access_control_policy_dialect }}"
      predefined:         "{{ set_access_control_policy_predefined }}"
      new_name:           "{{ set_access_control_policy_new_name }}"
  when: set_access_control_policy_name is defined and set_access_control_policy_policy_file is defined and set_access_control_policy_attributesrequired is defined
  notify: Commit Changes
