- name: Get all Federations
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.fed.federations.get_all
  register: ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    federation_ret_obj: "{{ ret_obj }}"