- name: Execute operation {{execute_rp_op_operation}} against reverse proxy
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.instance.execute
    isamapi:
      id: "{{ item }}"
      operation: "{{execute_rp_op_operation}}"
  with_items: "{{execute_rp_op_ids | default({}) }}"
  when: execute_rp_op_ids is defined and execute_rp_op_operation is defined