- name: Upload Mapping Rule - {{upload_mapping_rule_name}}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.mapping_rules.upload
    isamapi:
      name           : "{{ upload_mapping_rule_name }}"
      category       : "{{ upload_mapping_rule_category }}"
      upload_filename: "{{ upload_mapping_rule_upload_filename }}"
  when: upload_mapping_rule_name is defined and upload_mapping_rule_category is defined and upload_mapping_rule_upload_filename is defined
  notify: Commit Changes